### ISSUE TITLE
Install on Windows

### ISSUE THREAD

**Issue by danielsjf** [JeroenDM/acrobotics#3]
@JeroenDM, what are the requirements for the swig branch. Specifically [this line](https://github.com/JeroenDM/acrobotics/blob/431ef221d77a58b99c6563710874cb68eda03810/src/acrobotics/cpp/geometry.py#L16) does not work well in the imports. I've installed swig, but it is unclear how I should set the path/references.

```
Traceback (most recent call last):
  File "C:/data/workspace/acrobotics/examples/getting_started.py", line 11, in <module>
    from acrobotics.robot_examples import Kuka
  File "C:\data\workspace\acrobotics\src\acrobotics\robot_examples.py", line 3, in <module>
    from .robot import Robot, Tool
  File "C:\data\workspace\acrobotics\src\acrobotics\robot.py", line 7, in <module>
    from acrobotics.geometry import ShapeSoup
  File "C:\data\workspace\acrobotics\src\acrobotics\geometry.py", line 3, in <module>
    from acrobotics.shapes import Shape, Box, Polyhedron
  File "C:\data\workspace\acrobotics\src\acrobotics\shapes.py", line 6, in <module>
    from .cpp.geometry import Box as CppBox
  File "C:\data\workspace\acrobotics\src\acrobotics\cpp\geometry.py", line 17, in <module>
    _geometry = swig_import_helper()
  File "C:\data\workspace\acrobotics\src\acrobotics\cpp\geometry.py", line 16, in swig_import_helper
    return importlib.import_module('_geometry')
  File "C:\***\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_geometry'
```

**Comment by JeroenDM** [comment]
For future reference when I have a Windows pc to investigate the problem, some suggestions.

Try to build the swig bindings from source, on ubuntu I have done this in the past like this:
```bash
swig -c++ -python geometry.i
```

And then compile them using either some version of g++ [on windows](http://www.mingw.org/):
```bash
g++ -std=c++11 -O2 -fPIC -c src/geometry.cc geometry_wrap.cxx -I /<path_to_python_installation>/python3.6m -I include -I /usr/include/eigen3
g++ -std=c++11 -O2 -shared geometry.o geometry_wrap.o -o _geometry.so
```
Or using Visual Studio and it's C++ compiler.
